config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :pets, only: [:new, :create, :show, :index, :edit, :update, :destroy] do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:index, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :pet
end

app/models/pet.rb
class Pet < ApplicationRecord
    has_many :users, through: :bookings
    has_many :bookings
    belongs_to :user
    has_one_attached :photo
    validates :name, presence: true
    validates :description, presence: true
    validates :location, presence: true
    validates :breed, presence: true
    validates :price, presence: true
    geocoded_by :location
    after_validation :geocode, if: :will_save_change_to_location?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :pets
  has_many :bookings
  has_many :received_bookings, through: :pets, source: :bookings
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

    def index
      # @booking = Booking.find(params[:id])
      @bookings = Booking.all
      @pets = Pet.all
      @my_bookings = current_user.bookings
      @my_pets_bookings = current_user.received_bookings
    end

    def new
      @booking = Booking.new
      @pet = Pet.find(params[:pet_id])
    end

    def create
      @booking = Booking.new(booking_params)
      @pet = Pet.find(params[:pet_id])
      @booking.user = current_user
      @booking.pet = @pet
      @booking.save
      redirect_to bookings_path
    end

    def edit
      @booking = Booking.find(params[:id])
    end

    def update
      @booking = Booking.find(params[:id])
      @booking.status = params[:query]
      @booking.save!
      redirect_to bookings_path
    end

    private

    def booking_params
      params.require(:booking).permit(:start_date, :end_date, :status)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    if params[:query].present?
      sql_query = "breed ILIKE :query OR description ILIKE :query OR location ILIKE :query"
      @pets = Pet.where("breed ILIKE ?", "%#{params[:query]}%")
    else
      @pets = Pet.all
    end

    @markers = @pets.geocoded.map do |pet|
      {
        lat: pet.latitude,
        lng: pet.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { pet: pet }),
        image_url: helpers.asset_url('pink_paws.png')
      }
    end 
  end

  def show
    @pet = Pet.find(params[:id])
    @booking = Booking.new
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.user_id = current_user.id
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render 'new'
    end
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    @pet.update(pet_params)
    redirect_to pet_path(@pet)
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy
    redirect_to pets_path
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :description, :location, :breed, :price, :user_id, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<div class="container mt-5">
    <div class="card-dashboard">
        <div class="card-dashboard-image" style="background-image: url('<%= cl_image_path (@booking.pet.photo.key)%>')">
        </div>
        <div class="card-dashboard-content">
          <%= @booking.pet.name %><br>
          Location: <%= @booking.pet.location%><br>
          <%= @booking.pet.description %><br>
          Booking date: from <%= @booking.start_date %> to <%= @booking.end_date %><br>
          <%= @booking.pet.price %>€ per day
          <br>
          <br>
          See pet details
        </div>
        <div class="card-dashboard-booking-status">
        </div>
        <% if @booking.pet.user_id == current_user.id %>
        <%= simple_form_for @booking do |f| %>
        <%= f.input :status, :collection => ["Accept", "Reject"] %>
        <%= f.submit "Confirm status", class: "btn btn-primary" %>
    <%  end %>
    <% end  %>
      </div>
</div>

app/views/bookings/index.html.erb
<div class="container-olivia">
    <h1 class="h1-dashboard">Dashboard</h1>
    <br>
    <strong><p class="resizing-title">My bookings</p></strong>
  <% @my_bookings.each do |booking| %>
    <div class="card-dashboard">
      <div class="card-dashboard-image" style="background-image: url('<%= cl_image_path (booking.pet.photo.key)%>')">
      </div>
      <div class="card-dashboard-content">
        <span><i class="fas fa-map-marker-alt text-primary mr-2"></i><%= booking.pet.location%></span>
        <br>
        <br>
        <div class="align-center-petbreeddescription">
        <div class="pet-breed-font"><strong><%= booking.pet.name %> - <%= booking.pet.breed %><br></strong></div>
        <div class="border-bottom"></div>
        <p><%= booking.pet.description %></p>
        <i class="far fa-calendar-times"></i>
          <p>Booking date: from <%= booking.start_date %> to <%= booking.end_date %></p>
        </div>
        <div class="align-right-bookingpetprice">
        <%= booking.pet.price %>€ / day
        </div>
      </div>
      <div class="card-dashboard-booking-status">
        <div>
          <p><%= booking.status %></p>
          <%= link_to "View Booking", edit_booking_path(booking) %>
        </div>
      </div>
    </div>
  <% end %>
  
  <br>
  <br>
  <div class="booking-separator"></div>
  <br>
  <strong><p class="resizing-title">My pets</p></strong>
    <% @my_pets_bookings.each do |booking| %>
    <div class="card-dashboard">
      <div class="card-dashboard-image" style="background-image: url('<%= cl_image_path (booking.pet.photo.key)%>')">
      </div>
      <div class="card-dashboard-content">
        <br>
        <br>
        <div class="align-center-petbreeddescription">
        <div class="pet-breed-font"><strong><%= booking.pet.name %> - <%= booking.pet.breed %><br></strong></div>
        <div class="border-bottom"></div>
        <br>
        <i class="far fa-calendar-times"></i>
        Booking date: from <%= booking.start_date %> to <%= booking.end_date %><br>
        <br>
        </div>
        <br>
        <br>
        <div class="align-right-bookingpetprice">
        <%= booking.pet.price %>€ / day
        </div class="btn-bookpet">
      </div>
      <div class="card-dashboard-booking-status">
        <% if booking.status == 'pending' %>
        <%= link_to booking_path(booking, query: "accepted"), method: :patch, data: { confirm: "Are you sure?"} do %>
          <i class="fas fa-check-circle accepted-icon"></i>
        <% end %>
        <%= link_to booking_path(booking, query: "declined"), method: :patch, data: { confirm: "Are you sure?"} do %>
          <i class="fas fa-times-circle declined-icon"></i>
        <% end %>
        <% else %>
        <div class="">
          <p><%= booking.status %></p>
          <%= link_to "View Booking", edit_booking_path(booking) %>
        </div>
        <% end  %>
      </div>
    </div>
  <% end %>
</div>

app/views/bookings/new.html.erb
<%= simple_form_for [@pet, @booking] do |f| %>
<%=  f.input :start_date, as: :date %>
<%=  f.input :end_date, as: :date %>
<%= f.submit %>
<%  end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentAPet</title>
    <%= csrf_meta_tags %> <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application' %>
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <%= stylesheet_link_tag 'application', media: 'all',
    'data-turbolinks-track': 'reload' %> <%= javascript_pack_tag 'application',
    'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div class="main-container">
      <%= render "/shared/navbar" %>
      <%= yield %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= render "/shared/footer" %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
  <div class="home-banner d-flex align-items-end">
    <div class='home-banner-container-text'>
      <h2 class="banner-paragraph">Be in great company, <br>rent a pet!</h2>
      <div class="home-buttons-links">
        <%= link_to "See all pets", pets_path, class: "btn-seeallpets"%>
        <%= link_to "List a pet", new_pet_path, class: "btn-listapet"%>
      </div>
    </div>
  </div>

  <div class="container-olivia">
  <h2><strong>Rent the pet of your choice</strong></h2>
  <div class="cards">
  <div class="card" style="width: 18rem;">
    <div class="home-card-image rounded" style="background-image: url('https://images.unsplash.com/photo-1425082661705-1834bfd09dca?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1955&q=80')"></div>
    <div class="card-body">
      <strong><%= link_to "Homely hamsters", pets_path  %><h6 class="card-title"></h6></strong>
    </div>
  </div>

  <div class="card" style="width: 18rem;">
    <div class="home-card-image rounded" style="background-image: url('https://images.unsplash.com/photo-1530126483408-aa533e55bdb2?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=2002&q=80')"></div>
    <div class="card-body">
      <strong><%= link_to "Dozing dogs", pets_path  %><h6 class="card-title"></h6></strong>
    </div>
  </div>

  <div class="card" style="width: 18rem;">
    <div class="home-card-image rounded" style="background-image: url('https://images.unsplash.com/photo-1569591159212-b02ea8a9f239?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=634&q=80')"></div>
    <div class="card-body">
      <strong><%= link_to "Cool cats", pets_path  %><h6 class="card-title"></h6></strong>
    </div>
  </div>

  <div class="card" style="width: 18rem;">
    <div class="home-card-image rounded" style="background-image: url('https://images.unsplash.com/photo-1599824567234-b8bc5dbcd02e?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=675&q=80')"></div>
    <div class="card-body">
      <strong><%= link_to "Daring donkeys", pets_path  %><h6 class="card-title"></h6></strong>
    </div>
  </div>

  <div class="card" style="width: 18rem;">
    <div class="home-card-image rounded" style="background-image: url('https://images.unsplash.com/photo-1452857297128-d9c29adba80b?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1934&q=80')"></div>
    <div class="card-body">
      <strong><%= link_to "Relaxed rabbits", pets_path  %><h6 class="card-title"></h6></strong>
    </div>
  </div>
  </div>
  </div>

app/views/pets/_info_window.html.erb
<h2><%= pet.name %></h2>
<p><%= pet.location %></p>

app/views/pets/index.html.erb
<div class="d-flex">
  <div class="container w-50">
    <div class="col-lg-12">
      <h1>Pet Results...</h1>
      <% @pets.each do |pet| %>
      <div class="row">
        <div class="card mb-2 w-100">
          <div class="card-body d-flex">
            <!-- <img class="cd-img w-25" src="..." /> -->
            <div class="pet-card-img cd-img w-50 mr-2 rounded" style="background-image: url('<%= cl_image_path (pet.photo.key), crop: :fill %>')"></div>
            <div class="w-100">
              <div class="d-flex justify-content-between">
                <span
                  ><i class="fas fa-map-marker-alt text-primary mr-2"></i><%= pet.location
                  %></span
                >
                <a href="#"><i class="far fa-heart text-primary"></i></a>
              </div>
              <div class="border-bottom">
                <br>
                <%= link_to pet_path(pet) do %>
                <span class="font-weight-bold text-dark"
                  ><%= pet.name %> - <%= pet.breed %></span
                >
              </div>
              <% end %>
              <div>
                <p><%= pet.description %></p>
              </div>
              <div class="price d-flex justify-content-end w-100">
                <p><%= pet.price %>€ / Day</p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
  <div id="map" style="width: 50%; height: 100vh; position:sticky;" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/pets/new.html.erb
<div class="container mt-5">
    <div class="col-lg-6 offset-lg-3">
        <h1>Who will be joining us?</h1>
        <%= simple_form_for @pet do |f| %>
        <%=  f.input :name %>
        <%=  f.input :description %>
        <!-- <label for="form-address">Search for address</label>
        <input name=<%= params[:location] %> class="form-control" id= "form-address" type="search"> -->
    <%=  f.input :location, input_html: { type: "search", id: "form-address" } %>
        <%=  f.input :breed %>
        <%=  f.input :price %>
        <%= f.input :photo, as: :file %>
        <%= f.submit "Submit", class: "btn btn-primary" %>
        <%  end %>
    </div>
</div>

app/views/pets/show.html.erb
<div class="d-flex justify-content-center">
  <div class="container-show">
    <div class="card mb-3">
       <div class="pet-img-show" style="background-image: url('<%=cl_image_path(@pet.photo.key)%>')">
        </div>

        <div class="d-flex justify-content-space-between">

          <div class="box1">

          <div class="card-body text-left">
            <h5 class="card-title"><%= @pet.name %> - <%= @pet.breed %></h5>
            <div class="container-location">
              <div class="location-pet">
                <i class="fas fa-map-marker-alt text-primary mr-1"></i>
              </div>
                <h6 class="card-text"><medium><%= @pet.location %></medium></h6>
            </div>

          <div class="container-owner">
              <div class="rick">


                <h6 class="card-text"><strong>Owned by <%= @pet.user.email.split('@')[0].capitalize %></strong></h6>


              </div>
                <%= image_tag("rick.png", class: "avatar-bordered-medium") %>
          </div>
          <br>
          <p class="card-text">Description: <%= @pet.description%></p>
            <p class="card-text">Price: <span class="pet-price-value"><%= @pet.price%></span> euro </p>

              <%= link_to "Back", pets_path, class: "btn btn-outline-secondary btn-sm"%>
              <% if @pet.user_id == current_user.id %>
              <%= link_to "Remove Dog Listing", pet_path(@pet), class: "btn btn-outline-secondary btn-sm", method: :delete, data: { confirm: "Delete?" }%>
              <% end %>
          </div>
        </div>
        <div class="box2">
          <div class="container-show2">
            <div class="card mb-3 p-3">
              <% if @pet.user_id == current_user.id %>
              <h5><%= @pet.name %> is your <%= @pet.breed %></h5>
            <% else %>
            <h5 class="card2">Book this pet!</h5>
            <div class="">
              <%= simple_form_for [@pet, @booking] do |f| %>
              <%=  f.text_field :start_date, class: "start-date-field", data: {
                controller: "flatpickr",
                flatpickr_date_format: "Y-m-d",
                flatpickr_min_date: Time.zone.now
              } %>
              <%=  f.text_field :end_date, class: "end-date-field", data: {
                controller: "flatpickr",
                flatpickr_date_format: "Y-m-d",
                flatpickr_min_date: Time.zone.now,
                id: "end-date"
              } %>
                  <div class="border-top mt-3">
                    <br>
                    <span>Total:  </span><span id="total-price"></span>
                  </div>
              <%= f.submit class: "btn-bookpet mt-3"%>
              <%  end %>
            </div>
            <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="text-footer">
    <p>© 2021 Rent-a-pet, Inc. All rights reserved</p>
  </div>
  <div class="links">
    <a href="#">
      <i class="fab fa-fw fa-facebook-f"></i>
    </a>
    <a href="#">
      <i class="fab fa-fw fa-twitter"></i>
    </a>
    <a href="#">
      <i class="fab fa-fw fa-instagram"></i>
    </a>
   </div>
</div>

app/views/shared/_navbar.html.erb
<div class='navbar-lewagon'>
  <div class='container-home-daan'>
    <div class='home-icon'>
      <%= link_to root_path do  %>
      <i class="fas fa-paw  fa-2x" ></i>
      <% end %>
      <div class='home-navbar-text'><h3><strong>Rent-a-pet</strong></h3></div>
    </div>
    <div class='home-navbar-menu'>
      <div class='home-owner'><h6><%= link_to "See all pets", pets_path%></h6></div>
      <div class='home-owner'><h6><%= link_to "Become an owner", new_pet_path%></h6> </div>
      <div class="d-flex justify-content-center">
        <%= form_tag pets_path, method: :get do %>
        <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Look for a pet..."
        %>
      <% end %>
    </div>
      <div class="nav-item dropdown">
        <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://i.pinimg.com/originals/09/a5/c8/09a5c8eb3920af9cf2774c009a7b0d54.jpg" width="43" height="46"/>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <% if current_user %>
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          <%= link_to "Dashboard", bookings_path, class: "dropdown-item" %>
        <% else  %>
        <%= link_to "Log in", new_user_session_path, class: "dropdown-item" %>
        <%= link_to "Sign up", new_user_registration_path, class: "dropdown-item" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>